[package]
name = "lyrical"
version = "0.1.0"
edition = "2021"

[dependencies]
html2text = "0.12.5"
regex = "1.10.4"
reqwest = "0.12.4"
scraper = "0.19.0"
tokio = { version= "1.37.0", features=["full"] }
